export const ROUTES = {
  LOGIN: 'login',
  SIGNUP: 'sign-up',
  FORGOT_PASSWORD: 'forgot-password',
  CHANGE_PASSWORD: 'change-password',
  DASHBOARD: 'dashboard',
  COMPLETE_KYB_ONBOARDING: 'complete-kyb-onboarding',
  COMPLETE_ONBOARDING_DETAIL: 'detail',
  COMPLETE_KYC_ONBOARDING: 'complete-kyc-onboarding',
  MARKETS: 'markets',
  WALLET: 'wallet',
  MYINVESTMENT: 'my-investment',
  MYORDERS: 'my-orders',
  MYBOOKING: 'my-booking',
  DIVIDEND: 'dividend',
  CALCULATOR: 'investment-calculator',
  BUYBACKREQUEST: 'buyback-request',
  BUYBACK_ORDER_HISTORY: 'buyback-request/order-history',
  MARKETSDETAILS: 'detail',
  CREATE_ORDER: 'detail/create-order',
  INVITEFRIENDS: 'invite-friends',
  SETTINGS: 'settings',
  TERMS_AND_CONDITION: 'terms-and-condition',
  USER: 'user',
  P2PMARKET: 'p2p-market',
};
