import NiceModal from '@ebay/nice-modal-react';
import walletDepositModal from './components/modals/walletDepositModal/WalletDepositModal';
import AlertModal from './components/modals/alertModal/AlertModal';
import CongratulationsModal from './components/modals/congratulationsModal/CongratulationsModal';
import ChangePasswordModal from './components/modals/changePasswordModal/ChangePasswordModal';
import PropertyAdvisorSupport from './components/modals/propertyAdvisorSupport/PropertyAdvisorSupport';
import PreviewModal from './components/modals/previewModal/PreviewModal';
import TermConditionModal from './components/modals/termConditionModal/TermConditionModal';
import ViewModal from './components/modals/viewModal/ViewModal';
import TransactionDetailModal from './components/modals/transactionDetailModal/TransactionDetailModal';
import WalletWithdrawModal from './components/modals/walletWithdrawModal/WalletWithdrawModal';
import AddBankAccount from './components/modals/addBankAccount/AddBankAccount';
import AddUpiAccount from './components/modals/addUpiAccount/AddUpiAccount';
import QrCodeModal from './components/modals/qrCodeModal/QrCodeModal';
import NFTCertificateModal from './components/modals/nftCertificateModal/NFTCertificateModal';
import CreateOrderModal from './components/modals/createOrderModal/CreateOrderModal';
import GalleryModal from './components/modals/galleryModal/GalleryModal';
import CanvasModal from './components/modals/canvasModal/CanvasModal';
import BuybackCreateOrderModal from './components/modals/buybackCreateOrderModal/BuybackCreateOrderModal';

// Registeries
NiceModal.register('WalletDepositModal', walletDepositModal);
NiceModal.register('AlertModal', AlertModal);
NiceModal.register('CongratulationsModal', CongratulationsModal);
NiceModal.register('ChangePasswordModal', ChangePasswordModal);
NiceModal.register('PropertyAdvisorSupport', PropertyAdvisorSupport);
NiceModal.register('PreviewModal', PreviewModal);
NiceModal.register('CreateOrderModal', CreateOrderModal);
NiceModal.register('TermConditionModal', TermConditionModal);
NiceModal.register('ViewModal', ViewModal);
NiceModal.register('TransactionDetailModal', TransactionDetailModal);
NiceModal.register('WalletWithdrawModal', WalletWithdrawModal);
NiceModal.register('AddBankAccount', AddBankAccount);
NiceModal.register('AddUpiAccount', AddUpiAccount);
NiceModal.register('QrCodeModal', QrCodeModal);
NiceModal.register('NFTCertificateModal', NFTCertificateModal);
NiceModal.register('GalleryModal', GalleryModal);
NiceModal.register('CanvasModal', CanvasModal);
NiceModal.register('BuybackCreateOrderModal', BuybackCreateOrderModal);